### ISSUE TITLE
User profile view and Edit

### ISSUE THREAD

**Issue by omanjose** [Python-Abia/Get-a-Doc-Mobile#10]
The profile view will show
1. Profile photo
2. Account type
3. User profession
4. User email
5. User interests
6. User endorsements which are rating giving by other users, they can be added by custom and also have incremental ratings with the users that gave such endorsements

**Comment by nbrabant** [comment]
Hello! 
Is it just the act of create view and edit for user profile?

**Comment by omanjose** [comment]
Yes it is brother

**Comment by omanjose** [comment]
Done
